### ISSUE TITLE
Enhance coverage of serializers

### ISSUE THREAD

**Issue by loulecrivain** [wobcom/cosmo#21]
In order to start refactoring of some of the code, we need a better coverage of the serializer (ideal would be 100% of code covered)

**Comment by loulecrivain** [comment]
also check this error:
```
Info: Generating trma2061
Traceback (most recent call last):
  File "/nix/store/qfn07kpir8wbmcjykzi3xl6rlhh8rhhh-python3.11-cosmo-0.8.4/bin/.cosmo-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/qfn07kpir8wbmcjykzi3xl6rlhh8rhhh-python3.11-cosmo-0.8.4/lib/python3.11/site-packages/cosmo/__main__.py", line 80, in main
    serializer = RouterSerializer(device, cosmo_data['l2vpn_list'], cosmo_data["vrf_list"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qfn07kpir8wbmcjykzi3xl6rlhh8rhhh-python3.11-cosmo-0.8.4/lib/python3.11/site-packages/cosmo/serializer.py", line 36, in __init__
    match device["platform"]["manufacturer"]["slug"]:
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
